sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: V2gkJZk46/C2gUpInxDgFR5CHT+NUYgV0LDGp1tNg7PXbOv/vAR39Ra1JugjuMvuqtSQPER9So1pBWP8a1RiLJ7k5f3MnUjcr/DVf52g41wQYHUgJ9WV7bdJdpZve4EmtzRO0T779x/2aebiZ6G4/hpyTs7M1/8E0Ys1oJJXRz0ZJvKMAamd5hMxxptmVsyYHYo7blqpEhaaFy2IeNUVxkwE5FE3IbLmshewtgKyyabnLCVBLqxymNEwXcbcLK1800A30iQY21ejm7xsp9nGPz8Fzg+czyfdXT8bLMpMONHxVnWtbgvQuWGUL4riubfoXqvQdEzFKfiUcnJv/CNy7Uf6jW5a1Egafy4EAK4MTzZJMrIJoNrI5L4/JCRNAc3FLEAr2fMQwcl9Rc8anSGC6204atqsKCh2Buo9FFEtewY+rZdmodtmjA9i/2HUCzPvsy17MjvMeWRV3nNj5UqOo4hYBb3exAvFtwYHMpVD+CddWQhuscuyxQQIw1NW7smQUD3cHrIxW1nExJ0OeYNPHW7RsuzmDqv7LGqGpXGjuv7a1epHePpvawKqFcRHu2ewQraWclIE+2lPmz3aFh/P5UyTU+vbKEfmNjGOIQZjzVbcH2dvGIpg/W54lO7ma8qR6J6me/3OvJwtffKNrzwKgRb8Cx1X9h+AeTqOqmWiMOs=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Fool-Errant-Being-the-Memoirs-of-Francis-Anthony-Strelley-Esq-Citizen-of-Lucca_5755
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy